import json
import time
import hashlib
import urllib.request
from urllib.parse import urlparse, parse_qs

DB_URL = "https://raw.githubusercontent.com/kaisleen82-eng/vending/master/db.json"
_keys_cache = None
_keys_cache_time = 0
CACHE_TTL = 30


def _load_keys():
    global _keys_cache, _keys_cache_time
    now = time.time()
    if _keys_cache is not None and (now - _keys_cache_time) < CACHE_TTL:
        return _keys_cache
    try:
        req = urllib.request.Request(DB_URL)
        resp = urllib.request.urlopen(req, timeout=10)
        data = json.loads(resp.read().decode())
        _keys_cache = data
        _keys_cache_time = now
        return data
    except Exception:
        return _keys_cache or {}


def _hash(pw):
    return hashlib.sha256(pw.encode()).hexdigest()


CORS = {
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
    "Access-Control-Allow-Headers": "Content-Type",
}


def handler(request, response=None):
    path = request.path or "/"
    method = request.method

    if method == "OPTIONS":
        return {"statusCode": 200, "headers": CORS, "body": ""}

    if path == "/api/health":
        return _json(200, {"status": "ok"})

    if method == "GET" and path == "/api/get":
        parsed = urlparse(request.url or path)
        params = parse_qs(parsed.query)
        key = params.get("key", [None])[0]
        if not key:
            return _json(400, {"error": "Missing key"})
        keys = _load_keys()
        info = keys.get(key.upper().strip())
        if info:
            return _json(200, {"key": key, "valid": True})
        fallback = keys.get("SCRIPT")
        if fallback is not None:
            return _text(200, "ok")
        return _json(404, {"error": "Key not found"})

    if method == "POST" and path == "/api/login":
        body = _body(request)
        key = body.get("key", "").upper().strip()
        user = body.get("username", "").strip()
        pw = body.get("password", "")

        if not key or not user or not pw:
            return _json(200, {"success": False, "reason": "All fields required"})

        keys = _load_keys()
        info = keys.get(key)
        if not info:
            return _json(200, {"success": False, "reason": "Key not found. Only keys generated by the bot are valid."})
        if info.get("revoked"):
            return _json(200, {"success": False, "reason": "Key has been revoked"})
        if info.get("expires_at") and time.time() > info["expires_at"]:
            return _json(200, {"success": False, "reason": "Key has expired"})
        if not info.get("registered"):
            return _json(200, {"success": False, "reason": "Key not registered. Use /register in Discord first."})
        if info.get("username") != user:
            return _json(200, {"success": False, "reason": "Invalid username"})
        if info.get("password") != _hash(pw):
            return _json(200, {"success": False, "reason": "Invalid password"})

        return _json(200, {"success": True, "key": key, "username": user, "type": info.get("type_label", "N/A")})

    return _json(404, {"error": "Not found"})


def _body(request):
    try:
        raw = request.body or b"{}"
        if isinstance(raw, str):
            raw = raw.encode()
        return json.loads(raw)
    except Exception:
        return {}


def _json(code, data):
    return {
        "statusCode": code,
        "headers": {"Content-Type": "application/json", **CORS},
        "body": json.dumps(data),
    }


def _text(code, data):
    return {
        "statusCode": code,
        "headers": {"Content-Type": "text/plain; charset=utf-8", **CORS},
        "body": data,
    }
