import json
import time
import hashlib
import urllib.request
from flask import Flask, request as req, jsonify

app = Flask(__name__)

DB_URL = "https://raw.githubusercontent.com/kaisleen82-eng/vending/master/db.json"
_keys_cache = None
_keys_cache_time = 0
CACHE_TTL = 30


def _load_keys():
    global _keys_cache, _keys_cache_time
    now = time.time()
    if _keys_cache is not None and (now - _keys_cache_time) < CACHE_TTL:
        return _keys_cache
    try:
        resp = urllib.request.urlopen(DB_URL, timeout=10)
        data = json.loads(resp.read().decode())
        _keys_cache = data
        _keys_cache_time = now
        return data
    except Exception:
        return _keys_cache or {}


def _hash(pw):
    return hashlib.sha256(pw.encode()).hexdigest()


@app.after_request
def add_cors(response):
    response.headers["Access-Control-Allow-Origin"] = "*"
    response.headers["Access-Control-Allow-Methods"] = "GET, POST, OPTIONS"
    response.headers["Access-Control-Allow-Headers"] = "Content-Type"
    return response


@app.route("/api/health")
def health():
    return jsonify({"status": "ok"})


@app.route("/api/login", methods=["POST"])
def login():
    data = req.get_json(force=True) or {}
    key = data.get("key", "").upper().strip()
    user = data.get("username", "").strip()
    pw = data.get("password", "")

    if not key or not user or not pw:
        return jsonify({"success": False, "reason": "All fields required"})

    keys = _load_keys()
    info = keys.get(key)
    if not info:
        return jsonify({"success": False, "reason": "Key not found. Only keys generated by the bot are valid."})
    if info.get("revoked"):
        return jsonify({"success": False, "reason": "Key has been revoked"})
    if info.get("expires_at") and time.time() > info["expires_at"]:
        return jsonify({"success": False, "reason": "Key has expired"})
    if not info.get("registered"):
        return jsonify({"success": False, "reason": "Key not registered. Use /register in Discord first."})
    if info.get("username") != user:
        return jsonify({"success": False, "reason": "Invalid username"})
    if info.get("password") != _hash(pw):
        return jsonify({"success": False, "reason": "Invalid password"})

    return jsonify({"success": True, "key": key, "username": user, "type": info.get("type_label", "N/A")})
